GET https://shrouded-escarpment-43675.herokuapp.com/api/persons
###
GET https://shrouded-escarpment-43675.herokuapp.com/api/persons/1
###
POST https://shrouded-escarpment-43675.herokuapp.com/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Artodsddsadadsa Hellas",
  "number": "djsakdsa"

}
###
DELETE https://shrouded-escarpment-43675.herokuapp.com/api/persons/1621
### LOCALHOST
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/622245410e225ce4ccf1b9b9
###
POST http://localhost:3001/api/persons  HTTP/1.1
content-type: application/json

{
  "name": "Artodsddsadadsa Hellas",
  "number": "djsakdsa"

}
###
DELETE http://localhost:3001/api/persons/62203bbc19a18e13db918149

###
PUT http://localhost:3001/api/persons/622232d78d8a7b175f65dae7
content-type: application/json

{
  "name": "THIS WAS MADE BY PUT",
  "number": "3333333333333"
}